### ISSUE TITLE
Mistake in priority calculation

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/Cofoundry.Plugins.SiteMap#1]
Hello,

It seems there is a mistake in the file : Cofoundry.Plugins.SiteMap.CofoundryContentSiteMapResourceRegistration

        private decimal GetPriority(PageRoute pageRoute)
        {
            var isDirectoryDefaultPage = pageRoute.IsDirectoryDefaultPage();
            var isInSiteRoot = pageRoute.PageDirectory.IsSiteRoot();

            // Site/Language root
            if (isDirectoryDefaultPage && isDirectoryDefaultPage) return 1;
            // Directory root
            if (isDirectoryDefaultPage) return 0.8m;

            // Directory sub pages
            return 0.6m;
       }

I think it would be :
            if (**isInSiteRoot** && isDirectoryDefaultPage) return 1;

Regards

**Comment by HeyJoel** [comment]
Good spot, thanks! That will be in v0.4.1 which should be up on nuget shortly.
