### ISSUE TITLE
Bad format of priority in not US culture

### ISSUE THREAD

**Issue by dumboster** [cofoundry-cms/Cofoundry.Plugins.SiteMap#2]
Hello,
When we are not in US culture, the priority can be in a bad format: in fr-FR for instance, it is with a comma instead of a point.
Could you force the culture to invariant culture in order to prevent this problem?
Thanks

**Comment by HeyJoel** [comment]
I've fixed that as suggested and released it in v0.5.1, which should be on NuGet shortly.

**Comment by dumboster** [comment]
Great! Thanx!
