### ISSUE TITLE
sitemap.xml  file.

### ISSUE THREAD

**Issue by sourabhCofoundry** [cofoundry-cms/Cofoundry.Plugins.SiteMap#4]
Hi, HeyJoel Please let me know how to edit the sitemap.xml file. Because I want to change the base URL https://abc.com to https://www.abc.com

Thank you.

**Comment by HeyJoel** [comment]
The url will be resolved using the `ISiteUrlResolver` implementation, which by default will first try and get the value from config, falling back to the path of the incoming url (via HttpContext.Request).

So basically if you want to set the site root explicitly, do it in config e.g:

```json
{
  "Cofoundry": {
    "SiteUrlResolver:SiteUrlRoot": "https://www.example.com"
  }
}
```

**Comment by sourabhCofoundry** [comment]
okay. So basically are you saying I have set a URL in a appsetting.json file right?

**Comment by HeyJoel** [comment]
Yes.

**Comment by sourabhCofoundry** [comment]
Thanks HeyJoel it's working.
